import { StyleSheet } from "react-native";

const homeStyles = StyleSheet.create({
  menuBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#f0f0f8",
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    alignItems: "center",
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  welcome: {
    fontSize: 12,
    color: "#727785",
  },
  name: {
    fontSize: 16,
    fontWeight: "bold",
  },
searchBox: {
  flexDirection: "row",
  alignItems: "center",
  backgroundColor: "#f8f4ec",
  marginHorizontal: 15,
  marginBottom: 15,
  paddingHorizontal: 12,
  paddingVertical: 12,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: "#e8e8e8",
},

searchInput: {
  flex: 1,
  marginLeft: 8,
  color: "#111",
  fontSize: 14,
  padding: 0,
},
  banner: {
    height: 200,
    margin: 16,
    borderRadius: 16,
    overflow: "hidden",
    justifyContent: "center",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  bannerContent: {
    padding: 20,
    gap: 10,
  },
  marketplaceBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#2979FF",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 5,
  },
  marketplaceBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
  },
  bannerTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 32,
  },
  exploreBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#2979FF",
    borderRadius: 25,
    paddingHorizontal: 18,
    paddingVertical: 10,
    gap: 6,
  },
  exploreBtnText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    marginBottom: 16,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  catItem: {
    alignItems: "center",
    gap: 8,
  },
  iconBox: {
    width: 60,
    height: 60,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  catLabel: {
    fontSize: 12,
    color: "#333",
    textAlign: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 15,
    alignItems: "center",
    marginBottom: 12,
  },
  section: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
  },
  link: {
    color: "#0058be",
    fontSize: 12,
  },
  card: {
    width: 180,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#eee",
    overflow: "hidden",
    marginRight: 12,
  },
  cardImage: {
    width: "100%",
    height: 120,
  },
  featuredBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "#2979FF",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  featuredText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "600",
  },
  heartBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "#fff",
    borderRadius: 20,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
  },
  cardBody: {
    padding: 10,
    gap: 4,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111",
  },
  cardPrice: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2979FF",
  },
  recentCard: {
    flex: 1,
    margin: 5,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
  },
  recentImg: {
    width: "100%",
    height: 100,
  },
  recentTitle: {
    fontSize: 12,
  },
  recentPrice: {
    fontWeight: "bold",
    color: "#0058be",
  },
  sellCard: {
    backgroundColor: "#2979FF",
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 24,
    alignItems: "center",
    marginHorizontal: 16,
    marginVertical: 24,
  },
  iconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  sellTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
  },
  sellSubtitle: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 20,
  },
  postBtn: {
    backgroundColor: "#fff",
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
    paddingHorizontal: 32,
    gap: 8,
  },
  postBtnText: {
    color: "#2979FF",
    fontSize: 16,
    fontWeight: "600",
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingVertical: 10,
    justifyContent: "space-around",
  },
  tab: {
    alignItems: "center",
    gap: 4,
  },
  tabLabel: {
    fontSize: 11,
    color: "#888",
  },
  activeLabel: {
    color: "#2979FF",
    fontWeight: "600",
  },
  homeActive: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#2979FF",
    alignItems: "center",
    justifyContent: "center",
  },
  CategoryActive: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  sellBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#2979FF",
    alignItems: "center",
    justifyContent: "center",
  },
  notifBadge: {
    position: "absolute",
    top: -4,
    right: -6,
    backgroundColor: "#E53935",
    borderRadius: 10,
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  notifBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
  },
});

export default homeStyles;